server:
  port: 8094


spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/project_harmonia
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: project_harmonia
    password: 7070

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

logging:
  level:
    root: DEBUG
# 명확한 CORS 설정 (JWT 인증 시 필수 권장)
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
